on: [push]
  

env:
  node-version: 16.x

name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - run: dotnet publish -c Release Avalonia.AXAML.LanguageServer/Avalonia.AXAML.LanguageServer 

      - name: Compile extensions
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
      - run: npm run deploy
          
