on: [push]
  

env:
  node-version: 16.x

name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - run: dotnet publish -c Release Avalonia.AXAML.LanguageServer/Avalonia.AXAML.LanguageServer -o libs

      - name: Compile extensions
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
      - run: npm run deploy
          
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.OPEN_VSX }}

      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com